In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r'C:\Users\leepa\Documents\data_center_energy_prediction\data\processed\final_dataset.csv')
df

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,0,0,2016-01-26 16:00:00,0.000,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
1,0,0,2016-01-26 23:00:00,0.000,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
2,0,0,2016-02-17 21:00:00,0.000,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
3,0,0,2016-02-21 15:00:00,0.000,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
4,0,0,2016-03-03 00:00:00,0.000,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146006,1448,0,2016-11-22 21:00:00,3.100,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146007,1448,0,2016-11-30 02:00:00,3.375,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146008,1448,0,2016-12-08 08:00:00,4.275,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146009,1448,0,2016-12-16 23:00:00,3.125,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146010,1448,0,2016-12-18 23:00:00,3.775,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1

In [3]:
df['meter_reading'].describe()

count    1.460110e+05
mean     1.305317e+03
std      1.248158e+05
min      0.000000e+00
25%      5.381500e+00
50%      4.500000e+01
75%      1.738500e+02
max      1.972030e+07
Name: meter_reading, dtype: float64

In [4]:
df['timestamp']=pd.to_datetime(df['timestamp'],errors='coerce')

df=df.sort_values(['building_id','timestamp']).reset_index(drop=True)

In [5]:
df.dtypes

building_id                    int64
meter                          int64
timestamp             datetime64[us]
meter_reading                float64
site_id                        int64
primary_use                      str
square_feet                    int64
year_built                   float64
air_temperature              float64
cloud_coverage               float64
dew_temperature              float64
precip_depth_1_hr            float64
sea_level_pressure           float64
wind_direction               float64
wind_speed                   float64
dtype: object

In [6]:
df.head()

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,0,0,2016-01-26 16:00:00,0.0,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
1,0,0,2016-01-26 23:00:00,0.0,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
2,0,0,2016-02-17 21:00:00,0.0,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
3,0,0,2016-02-21 15:00:00,0.0,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
4,0,0,2016-03-03 00:00:00,0.0,0,Education,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1

In [7]:
df.tail()

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
146006,1448,0,2016-11-22 21:00:00,3.100,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146007,1448,0,2016-11-30 02:00:00,3.375,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146008,1448,0,2016-12-08 08:00:00,4.275,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146009,1448,0,2016-12-16 23:00:00,3.125,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1
146010,1448,0,2016-12-18 23:00:00,3.775,15,Office,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1

In [8]:
df.size

2190165

In [9]:
df.shape

(146011, 15)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 146011 entries, 0 to 146010
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   building_id         146011 non-null  int64
 1   meter               146011 non-null  int64
 2   timestamp           146011 non-null  datetime64[us]
 3   meter_reading       146011 non-null  float64
 4   site_id             146011 non-null  int64
 5   primary_use         146011 non-null  str
 6   square_feet         146011 non-null  int64
 7   year_built          146011 non-null  float64
 8   air_temperature     146011 non-null  float64
 9   cloud_coverage      146011 non-null  float64
 10  dew_temperature     146011 non-null  float64
 11  precip_depth_1_hr   146011 non-null  float64
 12  sea_level_pressure  146011 non-null  float64
 13  wind_direction      146011 non-null  float64
 14  wind_speed          146011 non-null  float64
dtypes: datetime64[us](1), float64(9), int64(4), str(1)
memory usage: 16.7 MB

In [11]:
#0.000 in meter reading so fixing it

df.loc[df['meter_reading']== 0, 'meter_reading']=pd.NA

In [12]:
df['meter_reading'].isna().sum()

np.int64(27755)

In [13]:
#Filling Missing meter readings as this corresponds to prediction
df['meter_reading']=(df.groupby('building_id')['meter_reading'].transform(lambda x: x.interpolate(method='linear')))

df['meter_reading']=(df.groupby('building_id')['meter_reading'].transform(lambda x: x.ffill().bfill()))


#Correct upto this much

In [14]:
df['meter_reading'].isna().sum()

np.int64(6)

In [15]:
df.isna().sum()

building_id           0
meter                 0
timestamp             0
meter_reading         6
site_id               0
primary_use           0
square_feet           0
year_built            0
air_temperature       0
cloud_coverage        0
dew_temperature       0
precip_depth_1_hr     0
sea_level_pressure    0
wind_direction        0
wind_speed            0
dtype: int64

In [16]:
df[df['meter_reading'].isna()][['building_id','timestamp','meter_reading']]

      building_id           timestamp  meter_reading
4036           53 2016-01-04 10:00:00            NaN
4037           53 2016-01-18 20:00:00            NaN
4038           53 2016-01-26 19:00:00            NaN
4039           53 2016-02-10 22:00:00            NaN
4040           53 2016-03-11 21:00:00            NaN
4041           53 2016-12-04 12:00:00            NaN

In [17]:
df['meter_reading']=(df.groupby('building_id')['meter_reading'].transform(lambda x: x.ffill().bfill()))

In [18]:
df.isna().sum()

building_id           0
meter                 0
timestamp             0
meter_reading         6
site_id               0
primary_use           0
square_feet           0
year_built            0
air_temperature       0
cloud_coverage        0
dew_temperature       0
precip_depth_1_hr     0
sea_level_pressure    0
wind_direction        0
wind_speed            0
dtype: int64

In [19]:
#Even after Interpolating these 6 missing values cannot be filled so the only solution is to drop them
df = df.dropna(subset=['meter_reading']).reset_index(drop=True)

In [20]:
df.isna().sum()

building_id           0
meter                 0
timestamp             0
meter_reading         0
site_id               0
primary_use           0
square_feet           0
year_built            0
air_temperature       0
cloud_coverage        0
dew_temperature       0
precip_depth_1_hr     0
sea_level_pressure    0
wind_direction        0
wind_speed            0
dtype: int64

In [21]:
df['meter_reading'].isna().sum()

np.int64(0)

In [22]:
### There are two object columns timestamp and primary_use we need to convert it into meaningful numbers
# Here we need to use Encoding 
# We are using label encoding as

In [23]:
df['hour'] = df['timestamp'].dt.hour
df['day'] = df['timestamp'].dt.day
df['weekday'] = df['timestamp'].dt.weekday
df['month'] = df['timestamp'].dt.month
df['day'].isin([5,6]).astype(int)

0         0
1         0
2         0
3         0
4         0
         ..
146000    0
146001    0
146002    0
146003    0
146004    0
Name: day, Length: 146005, dtype: int64

In [24]:
from sklearn.preprocessing import LabelEncoder
encode=LabelEncoder()
df['primary_use']=encode.fit_transform(df['primary_use'])

In [25]:
df['primary_use'].unique()

array([ 0,  4,  6,  1,  7, 11,  8,  9, 15,  2, 10,  3, 14, 13,  5, 12])

In [26]:
df

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed,hour,day,weekday,month
0,0,0,2016-01-26 16:00:00,252.547,0,0,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1,16,26,1,1
1,0,0,2016-01-26 23:00:00,252.547,0,0,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1,23,26,1,1
2,0,0,2016-02-17 21:00:00,252.547,0,0,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1,21,17,2,2
3,0,0,2016-02-21 15:00:00,252.547,0,0,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1,15,21,6,2
4,0,0,2016-03-03 00:00:00,252.547,0,0,7432,2008.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1,0,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146000,1448,0,2016-11-22 21:00:00,3.100,15,6,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1,21,22,1,11
146001,1448,0,2016-11-30 02:00:00,3.375,15,6,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1,2,30,2,11
146002,1448,0,2016-12-08 08:00:00,4.275,15,6,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1,8,8,3,12
146003,1448,0,2016-12-16 23:00:00,3.125,15,6,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1,23,16,4,12
146004,1448,0,2016-12-18 23:00:00,3.775,15,6,92271,2001.0,17.2,0.0,7.8,0.0,1015.9,160.0,3.1,23,18,6,12

In [27]:
# Implementing LAG Features
df['lag_1h']  = df.groupby('building_id')['meter_reading'].shift(1)
df['lag_24h'] = df.groupby('building_id')['meter_reading'].shift(24)
df['lag_48h'] = df.groupby('building_id')['meter_reading'].shift(48)
df['y_1h']  = df.groupby('building_id')['meter_reading'].shift(-1)
df['y_24h'] = df.groupby('building_id')['meter_reading'].shift(-24)
df['y_48h'] = df.groupby('building_id')['meter_reading'].shift(-48)
df=df.drop(columns=['timestamp'])

In [28]:
df = df.dropna(subset=['lag_1h','lag_24h','lag_48h','y_1h','y_24h','y_48h'])

In [29]:
df

,building_id,meter,meter_reading,site_id,primary_use,square_feet,year_built,air_temperature,cloud_coverage,dew_temperature,...,hour,day,weekday,month,lag_1h,lag_24h,lag_48h,y_1h,y_24h,y_48h
1206,34,0,310.4280,0,4,42731,2002.0,27.2,0.0,12.8,...,1,1,4,1,310.4280,310.4280,310.4280,310.4280,310.4280,310.4280
1207,34,0,310.4280,0,4,42731,2002.0,27.2,0.0,12.8,...,1,1,4,1,310.4280,310.4280,310.4280,310.4280,310.4280,310.4280
1208,34,0,310.4280,0,4,42731,2002.0,25.6,0.0,12.2,...,1,1,4,1,310.4280,310.4280,310.4280,310.4280,310.4280,310.4280
1209,34,0,310.4280,0,4,42731,2002.0,23.9,4.0,10.6,...,1,1,4,1,310.4280,310.4280,310.4280,310.4280,310.4280,310.4280
1210,34,0,310.4280,0,4,42731,2002.0,22.8,0.0,10.6,...,1,1,4,1,310.4280,310.4280,310.4280,310.4280,310.4280,310.4280
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142478,1366,1,4.7588,15,6,87977,1947.0,17.2,0.0,7.8,...,0,25,0,4,5.3368,5.3815,5.3815,5.1528,22.4572,3.5774
142479,1366,1,5.1528,15,6,87977,1947.0,17.2,0.0,7.8,...,5,1,6,5,4.7588,5.3815,5.3815,415.8420,11.2922,41.1250
142480,1366,2,415.8420,15,6,87977,1947.0,17.2,0.0,7.8,...,17,2,0,5,5.1528,5.3815,5.3815,5.8154,272.7710,3.6024
142481,1366,1,5.8154,15,6,87977,1947.0,17.2,0.0,7.8,...,23,3,1,5,415.8420,5.3815,5.3815,248.7330,21.2450,97.0750
142482,1366,2,248.7330,15,6,87977,1947.0,17.2,0.0,7.8,...,5,14,5,5,5.8154,5.3815,5.3815,37.7750,26.2378,4.4501

In [30]:
df.groupby('building_id')[['meter_reading','lag_1h','lag_24h','lag_48h']].agg(['min','max','mean'])

            meter_reading                            lag_1h            \
                      min       max         mean        min       max
building_id
34               310.4280   310.428   310.428000   310.4280   310.428
54               623.5870   623.587   623.587000   623.5870   623.587
75               928.6280   928.628   928.628000   928.6280   928.628
110              172.4570   172.457   172.457000   172.4570   172.457
167                2.9307   403.066   221.854570     2.9307   401.167
...                   ...       ...          ...        ...       ...
1322              89.7201  2712.070  1929.240467    89.7201  2712.070
1323             224.0000   224.000   224.000000  3761.5000  3761.500
1342               0.6022   107.794    75.760479     0.7163   107.794
1354               0.1129  1280.780     2.109303     0.1129  1280.780
1366               2.7491   695.005     6.824888     2.7491   695.005

                           lag_24h                            lag_48h  \
                    mean       min        max         mean        min
building_id
34            310.428000  310.4280   310.4280   310.428000   310.4280
54            623.587000  623.5870   623.5870   623.587000   623.5870
75            928.628000  928.6280   928.6280   928.628000   928.6280
110           172.457000  172.4570   172.4570   172.457000   172.4570
167           212.895420    2.9307   167.9300    72.164415     0.3165
...                  ...       ...        ...          ...        ...
1322         1930.428336  150.5260  2712.0700  2069.389908  2097.3100
1323         3761.500000  244.0000   244.0000   244.000000   188.0000
1342           75.787835   54.6987   107.7940    75.777306    62.6750
1354            1.659007    0.1129     0.1129     0.112900     0.1129
1366            6.718015    5.3815     5.3815     5.381500     5.3815


                     max         mean
building_id
34            310.428000   310.428000
54            623.587000   623.587000
75            928.628000   928.628000
110           172.457000   172.457000
167            98.612500    37.810130
...                  ...          ...
1322         2097.310000  2097.310000
1323          188.000000   188.000000
1342           88.390013    75.536184
1354            0.112900     0.112900
1366          426.612000     5.566549

[77 rows x 12 columns]

In [31]:
#Here we Can see some Buildings are useless and repeats the reading
useless_buildings=(df.groupby('building_id')['meter_reading'].std().reset_index().query('meter_reading == 0'))
useless_buildings

    building_id  meter_reading
0            34            0.0
1            54            0.0
2            75            0.0
3           110            0.0
10          227            0.0
14          265            0.0
16          305            0.0
17          472            0.0
18          480            0.0
19          484            0.0
20          698            0.0
21          708            0.0
23          751            0.0
25          781            0.0
29          859            0.0
44         1046            0.0
48         1215            0.0
70         1316            0.0

In [32]:
# now we have to drop them 

df=df[~df['building_id'].isin(useless_buildings['building_id'])]

In [33]:
df=df.reset_index(drop=True)

In [34]:
# Finalcheck before exporting
df.isna().sum()

building_id           0
meter                 0
meter_reading         0
site_id               0
primary_use           0
square_feet           0
year_built            0
air_temperature       0
cloud_coverage        0
dew_temperature       0
precip_depth_1_hr     0
sea_level_pressure    0
wind_direction        0
wind_speed            0
hour                  0
day                   0
weekday               0
month                 0
lag_1h                0
lag_24h               0
lag_48h               0
y_1h                  0
y_24h                 0
y_48h                 0
dtype: int64

In [35]:
df.to_csv('c:/Users/leepa/Documents/data_center_energy_prediction/data/processed/feateng_dataset.csv',index=False)

In [36]:
df

,building_id,meter,meter_reading,site_id,primary_use,square_feet,year_built,air_temperature,cloud_coverage,dew_temperature,...,hour,day,weekday,month,lag_1h,lag_24h,lag_48h,y_1h,y_24h,y_48h
0,167,0,57.5400,2,4,86323,1956.0,17.2,0.0,7.8,...,14,19,6,6,223.8830,61.1932,57.6800,280.9260,77.630000,85.9500
1,167,1,280.9260,2,4,86323,1956.0,17.2,0.0,7.8,...,6,22,2,6,57.5400,118.5200,31.7707,309.1310,324.500000,12.2035
2,167,1,309.1310,2,4,86323,1956.0,17.2,0.0,7.8,...,2,24,4,6,280.9260,11.7228,5.8614,2.9307,252.228667,2.9307
3,167,3,2.9307,2,4,86323,1956.0,17.2,0.0,7.8,...,3,25,5,6,309.1310,82.0129,5.8614,2.9307,179.957333,83.9500
4,167,3,2.9307,2,4,86323,1956.0,17.2,0.0,7.8,...,2,28,1,6,2.9307,78.2100,5.8614,61.9700,107.686000,23.4457
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46849,1366,1,4.7588,15,6,87977,1947.0,17.2,0.0,7.8,...,0,25,0,4,5.3368,5.3815,5.3815,5.1528,22.457200,3.5774
46850,1366,1,5.1528,15,6,87977,1947.0,17.2,0.0,7.8,...,5,1,6,5,4.7588,5.3815,5.3815,415.8420,11.292200,41.1250
46851,1366,2,415.8420,15,6,87977,1947.0,17.2,0.0,7.8,...,17,2,0,5,5.1528,5.3815,5.3815,5.8154,272.771000,3.6024
46852,1366,1,5.8154,15,6,87977,1947.0,17.2,0.0,7.8,...,23,3,1,5,415.8420,5.3815,5.3815,248.7330,21.245000,97.0750
46853,1366,2,248.7330,15,6,87977,1947.0,17.2,0.0,7.8,...,5,14,5,5,5.8154,5.3815,5.3815,37.7750,26.237800,4.4501

In [37]:
df.isna().sum().sum()== 0

np.True_

In [38]:
df.shape

(46854, 24)

In [39]:
df.dtypes

building_id             int64
meter                   int64
meter_reading         float64
site_id                 int64
primary_use             int64
square_feet             int64
year_built            float64
air_temperature       float64
cloud_coverage        float64
dew_temperature       float64
precip_depth_1_hr     float64
sea_level_pressure    float64
wind_direction        float64
wind_speed            float64
hour                    int32
day                     int32
weekday                 int32
month                   int32
lag_1h                float64
lag_24h               float64
lag_48h               float64
y_1h                  float64
y_24h                 float64
y_48h                 float64
dtype: object

In [40]:
i = 1500
print("meter_reading (previous row):", df.loc[i-1, 'meter_reading'])
print("lag_1h (current row):", df.loc[i, 'lag_1h'])

meter_reading (previous row): 10.92
lag_1h (current row): 10.92

In [41]:
i=1400
print(df.iloc[i],['building_id'])
print(df.iloc[i-1],['building_id'])

building_id             188.00
meter                     0.00
meter_reading            10.92
site_id                   2.00
primary_use               6.00
square_feet           23549.00
year_built             1941.00
air_temperature          21.70
cloud_coverage            0.00
dew_temperature          -3.90
precip_depth_1_hr         0.00
sea_level_pressure     1017.60
wind_direction          100.00
wind_speed                3.60
hour                      8.00
day                       1.00
weekday                   4.00
month                     1.00
lag_1h                   10.92
lag_24h                  10.92
lag_48h                  10.92
y_1h                     10.92
y_24h                    10.92
y_48h                    10.92
Name: 1400, dtype: float64 ['building_id']
building_id             188.00
meter                     0.00
meter_reading            10.92
site_id                   2.00
primary_use               6.00
square_feet           23549.00
year_built             1941.00
air_temperature          18.90
cloud_coverage            0.00
dew_temperature          -3.30
precip_depth_1_hr         0.00
sea_level_pressure     1017.40
wind_direction          100.00
wind_speed                2.60
hour                      8.00
day                       1.00
weekday                   4.00
month                     1.00
lag_1h                   10.92
lag_24h                  10.92
lag_48h                  10.92
y_1h                     10.92
y_24h                    10.92
y_48h                    10.92
Name: 1399, dtype: float64 ['building_id']